spring:
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:EMOJI
logging.level.org.hibernate: DEBUG

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true