apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: inclusion-backend-api
  namespace: default
  annotations:
    autoscaling.knative.dev/min-scale: "5"
  labels:
    app.kubernetes.io/part-of: inclusion
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  source:
    git:
      url: https://github.com/fklein82/emoji-inclusion.git
      ref:
        branch: main
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: "/v3/api-docs"
      system: emoji-world
      owner: team-vmware-tanzu-se
      description: "A set of API endpoints to manage the resources within the inclusion app."
###### Specific GITOPS to push code into git ####
  - name: gitops_server_address
    value: https://github.com/
  - name: gitops_repository_owner
    value: fklein82
  - name: gitops_repository_name
    value: tap-deliverables
  - name: gitops_ssh_secret
    value: git-ssh
  - name: gitops_user_email
    value: sa-tanzu@vmware.com
  - name: gitops_commit_message
    value: "Commit message from dev cluster workload"
###### END Specific GITOPS to push code into git ####
###### Specific GITOPS pull request ####
#  - name: gitops_server_kind
#    value: github
#  - name: gitops_commit_branch
#    value: dev
#  - name: gitops_pull_request_title
#    value: "app ready for review from dev workload"
#  - name: gitops_pull_request_body
#    value: "generated by tanzu-java-web-app supply chain from dev workload"
###### END Specific GITOPS pull request ####

